Release/17.0.0
EtherCorp/u_project pull request #18
Opened 2017-10-12 13:36 UTC by MonodetH

* Implements model layer
* Exposes model through an API REST
* Supports Create and Read operations for all tables

2017-10-26 21:35 UTC, dochoaj requested changes
En general está bien ordenado el proyecto. Me gustaría, eso si, que sacaran el proyecto del directorio unicorn api. Si el proyecto va a terminar teniendo subdirectorios, entonces es mejor separarlos en forma de repos.

2017-10-26 21:35 UTC, dochoaj commented on README.md
> +- Change to default postgres user `sudo -u postgres -i`
El database.yml, secrets.yml y cable.yml deberían estar gitignoreados y deberían crearse en el repo archivos tipo database.yml.default, que cada developer debe especializar. Así no se pisan las configs.

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/Gemfile
> +gem 'grape'
Fijar versiones

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/Gemfile
> +gem 'grape-entity'
Fijar versiones

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/consults.rb
> +        consult = Consult.new params
El api no tiene por que saber que existen métodos de activerecord, el modelo `Consult` debería tener un método de clase que permita crear instancias a partir de parámetros.

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/consults.rb
> +          present Consult.find_by(id: params[:consult_id]),
Lo mismo acá, quitar del api las referencias a ActiveRecord

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/consults.rb
> +            present Consult.find_by(id: params[:consult_id]).movements,
Lo mismo, es el último comentario que dejo al respecto. Por favor revisar el API completa

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Como les comentaba más arriba, este archivo debería ir gitignored.

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/medical_centers.rb
> +            present MedicalCenter.find_by(id: params[:id]).professionals,
Qué pasa si no encuentro el elemento? Qué retorna el API?

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/medical_centers.rb
> +        med_center.save!
Qué pasa si no puedo crear? Qué retorna el API?

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/app/api/v1/consults.rb
> +                document.save!
En general, no se usan métodos forzados (los que terminan en `!`). Acá el flujo debería ser `document = Document.create_with_params(params)` y luego `error 422 unless document` o algo así. Es el único caso que voy a comentar, revisen toda el API.

2017-10-26 21:35 UTC, dochoaj commented on unicorn-api/db/migrate/20171010235512_create_specialities.rb
> +    add_index :specialities, :name, unique: true
En general, debería haber otra migración que añada los índices de las tablas. Las migraciones deben tener una y solo una responsabilidad. Es el único caso que voy a comentar, revisen todas las migraciones.

2017-10-27 05:22 UTC, MonodetH commented on unicorn-api/app/api/v1/consults.rb
> +        consult = Consult.new params
No entiendo a lo que se refiere. En este caso se debería crear un método `create` para luego hacer `consult = Consult.create params`?

2017-10-27 05:25 UTC, MonodetH commented on unicorn-api/app/api/v1/consults.rb
> +          present Consult.find_by(id: params[:consult_id]),
Aquí sería `consult = Consult.find_by_id params[:consult_id]`?

2017-11-09 02:36 UTC, closed without merging